name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'
  

#   pull_request:
#     tag: 
#      - "*"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Check output
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        echo $RELEASE_VERSION
        echo ${{ steps.vars.outputs.tag }}
    
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}"
        
    - name: Scan current projects
      uses: anchore/scan-action@v2
      with:
        path: "."
            
    - name: Build the Docker images
      run: docker build -t ${{secrets.DOCKER_USER}}/file-server:${GITHUB_REF##*/} .
      
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/file-server:${GITHUB_REF##*/}