name: Docker Image CI

on:
  push:
    branches: [main]

# on:
#   push:
#     tags:
#      - "*"
#   pull_request:
#     tags: 
#      - "*"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
        
    - name: Scan current project
      uses: anchore/scan-action@v2
      with:
        path: "."
            
    - name: Build the Docker image
      run: docker build -t ${{secrets.DOCKER_USER}}/file-server:${GITHUB_REF##*/} .
      
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/file-server:${GITHUB_REF##*/}